# Generated by Django 5.1.2 on 2024-11-20 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Electronics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('unit', models.CharField(max_length=20)),
                ('date_added', models.DateField()),
                ('PO_number', models.CharField(max_length=50)),
                ('year_quarter', models.CharField(max_length=10)),
                ('serial_number', models.CharField(max_length=50)),
                ('obsolete', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ItemLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(max_length=50)),
                ('current_quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ITSupplies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('unit', models.CharField(max_length=20)),
                ('date_added', models.DateField()),
                ('PO_number', models.CharField(max_length=50)),
                ('year_quarter', models.CharField(max_length=10)),
                ('serial_number', models.CharField(max_length=50)),
                ('obsolete', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Janitorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('unit', models.CharField(max_length=20)),
                ('date_added', models.DateField()),
                ('PO_number', models.CharField(max_length=50)),
                ('year_quarter', models.CharField(max_length=10)),
                ('serial_number', models.CharField(max_length=50)),
                ('obsolete', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('unit', models.CharField(max_length=20)),
                ('date_added', models.DateField()),
                ('PO_number', models.CharField(max_length=50)),
                ('year_quarter', models.CharField(max_length=10)),
                ('serial_number', models.CharField(max_length=50)),
                ('obsolete', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RequestLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('requestor', models.CharField(max_length=50)),
                ('request_number', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(max_length=50)),
                ('admin', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('superadmin', 'Superadmin'), ('admin', 'Admin'), ('viewer', 'Viewer')], default='viewer', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
                ('item_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('unit', models.CharField(max_length=20)),
                ('purpose', models.TextField(null=True)),
                ('RF_number', models.CharField(max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=50)),
                ('serial_number', models.CharField(default='', max_length=50)),
                ('requestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
