# Generated by Django 5.1.2 on 2024-11-21 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_janitorial_po_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electronics',
            name='obsolete',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='electronics',
            name='serial_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='itsupplies',
            name='obsolete',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='itsupplies',
            name='serial_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='office',
            name='obsolete',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='office',
            name='serial_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='serial_number',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
