# Generated by Django 5.1.2 on 2024-11-22 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_electronics_obsolete_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestlogs',
            name='admin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
