# Generated by Django 5.1.2 on 2024-12-10 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_requestlogs_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestlogs',
            name='request_number',
            field=models.CharField(max_length=50),
        ),
    ]
