# Generated by Django 5.1.2 on 2024-10-31 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_janitorial_office'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(max_length=50)),
                ('current_quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RequestLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('requestor', models.CharField(max_length=50)),
                ('request_number', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(max_length=50)),
                ('admin', models.CharField(max_length=50)),
            ],
        ),
    ]
