# Generated by Django 5.1.2 on 2024-12-12 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_requestlogs_request_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electronics',
            name='year_quarter',
        ),
        migrations.RemoveField(
            model_name='itsupplies',
            name='year_quarter',
        ),
        migrations.RemoveField(
            model_name='janitorial',
            name='year_quarter',
        ),
        migrations.RemoveField(
            model_name='office',
            name='year_quarter',
        ),
        migrations.AddField(
            model_name='electronics',
            name='brand',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='electronics',
            name='model',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='electronics',
            name='quarter',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='electronics',
            name='year',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='itsupplies',
            name='brand',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='itsupplies',
            name='model',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='itsupplies',
            name='quarter',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='itsupplies',
            name='year',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='janitorial',
            name='brand',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='janitorial',
            name='model',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='janitorial',
            name='quarter',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='janitorial',
            name='year',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='office',
            name='brand',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='office',
            name='model',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='office',
            name='quarter',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='office',
            name='year',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
