# Generated by Django 5.1.2 on 2024-11-05 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_itemlogs_requestlogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='purpose',
            field=models.TextField(null=True),
        ),
    ]
