# Generated by Django 5.1.2 on 2024-12-12 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_electronics_quarter_alter_electronics_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemlogs',
            name='admin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
