# Generated by Django 5.1.2 on 2024-12-12 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_itemlogs_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='date_received',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
